"""initial_schema

Revision ID: a95e324ab3b7
Revises: 
Create Date: 2026-02-08 10:03:05.328587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95e324ab3b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_contact_type', sa.Enum('phone', 'email', name='contact_type_enum', create_constraint=True), nullable=False),
    sa.Column('requester_contact_value', sa.String(length=255), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('target_contact_type', sa.Enum('phone', 'email', name='contact_type_enum', create_constraint=True), nullable=False),
    sa.Column('target_contact_value', sa.String(length=255), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'granted', 'revoked', 'expired', name='consent_status_enum', create_constraint=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_contact_type', 'requester_contact_value', 'target_contact_type', 'target_contact_value', 'scope', name='uq_consent_requester_target_scope')
    )
    op.create_index('ix_consent_requester_lookup', 'consent_requests', ['requester_contact_type', 'requester_contact_value'], unique=False)
    op.create_index(op.f('ix_consent_requests_target_contact_value'), 'consent_requests', ['target_contact_value'], unique=False)
    op.create_index('ix_consent_status', 'consent_requests', ['status', 'expires_at'], unique=False)
    op.create_index('ix_consent_target_lookup', 'consent_requests', ['target_contact_type', 'target_contact_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consent_target_lookup', table_name='consent_requests')
    op.drop_index('ix_consent_status', table_name='consent_requests')
    op.drop_index(op.f('ix_consent_requests_target_contact_value'), table_name='consent_requests')
    op.drop_index('ix_consent_requester_lookup', table_name='consent_requests')
    op.drop_table('consent_requests')
    # ### end Alembic commands ###
